source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://github.com/Wwxd-Sun/ModuleSpece.git'   # 私有库
use_frameworks!

target 'UserMoudle_Example' do
  pod 'UserMoudle', :path => '../'

end
